# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a715cfc4533259f268aed68d7345bbab897a4e9cc1b4b09bba84a7828777c43050f6cd022f4c24c091c5d1479bb8c7a2b5e8663e9af36bf12e70664cec8aac4

test:
  secret_key_base: 64a9b35aa15c74bd796baf6403ed44923228ecbc6ac0f4b1afe0ab1753cf11412015aef8b77968cfa2d522c0fe66220b0e629ef15ccf2ee3a7471b7265dc97a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
